### ISSUE TITLE
About  operating environment and framework

### ISSUE THREAD

**Issue by Danee-wawawa** [mhy12345/Chinese-Character-Style-Transfer#1]
Hi, thank you for your work. Can you share your operating environment and framework? ^_^

**Comment by mhy12345** [comment]
Sorry, It has been long time since I did this job. So the environment was removed. But I don't think it matters. Just use Linux & Anaconda3 & Python3.7, install every missing packaged should be okay.

**Comment by Danee-wawawa** [comment]
OK, thank you~
